### PR TITLE
Use concurrent-ruby hash and map

### PR DESCRIPTION
**Pull request by BlakeWilliams**
This changes flay to use concurrent hashes and maps instead of the
stdlib hash.

This pulls in the changes Brian made in https://github.com/codeclimate/codeclimate-duplication/pull/33

### CODE REVIEW

**Comment by BlakeWilliams** [comment]
cc @codeclimate/review

**Comment by MattMSumner** [comment]
This looks reasonable to me... without diving into `Concurrent`

**Comment by mxie** [comment]
This looks reasonable to me as well. I think it might be worth explaining the difference between `Concurrent::Map` and `Concurrent::Hash` for `identical` and `masses` though.

**Comment by BlakeWilliams** [comment]
I didn't write it, so I'm not 100% sure the reason behind the change.

I do know that Map is more performant but isn't thread safe like Hash. I didn't dive deep enough into flay to understand why we'd use Map for `identical` and `not masses`.

**Pull request merged**
